const Log = require("./logger");

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJrdGhlbmlwYUBnaXRhbS5pbiIsImV4cCI6MTc4MDgxMTIxNSwiaWF0IjoxNzgwODEwMzE1LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiYzc0YjcyM2EtODhhOC00YzY4LTkzYTAtNjllNTEwY2E2Mzk3IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoidGhlbmlwYWxsaSBraXJhbiBrdW1hciIsInN1YiI6IjAyMGI2YzM0LTQyMzItNGYxYy1iNDU3LWIwNGU4MGIxOTFlZiJ9LCJlbWFpbCI6Imt0aGVuaXBhQGdpdGFtLmluIiwibmFtZSI6InRoZW5pcGFsbGkga2lyYW4ga3VtYXIiLCJyb2xsTm8iOiIyMDIzMDAyNDYyIiwiYWNjZXNzQ29kZSI6IndnS3RnWiIsImNsaWVudElEIjoiMDIwYjZjMzQtNDIzMi00ZjFjLWI0NTctYjA0ZTgwYjE5MWVmIiwiY2xpZW50U2VjcmV0IjoiQXlmbUdGdWFGdWNneWpxSyJ9.3P2mliW7r500XdFXFLpUUfmpV9or2WLO0xN5iIYeun4";

Log(
  "backend",
  "info",
  "service",
  "Logger Initialized Successfully",
  token
);